name: Sync Fork

on:
  schedule:
    - cron: '5 */6 * * *' # At minute 5 past every 6th hour..
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          owner: linuxserver
          base: master
          head: master
          merge_method: merge
          pr_message: 'Sync changes from upstream  to downstream'
          pr_title: Fork Sync
          auto_approve: true
          auto_merge: true
          
